[tool.poetry]
name = "ratpack"
version = "0.1.0"
description = "Packing away bits and bytes"
authors = ["Ryan Siemens <ryanjsiemens@gmail.com>"]
license = "Apache License 2.0"
readme = "README.txt"

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
ruff = "^0.15.12"
msgpack = "^1.1.2"
cbor2 = "^6.1.0"
py-ubjson = "^0.16.1"
mypy = "^2.1.0"
cython = "^3.2.4"

[tool.ruff.lint]
select = ["PL", "I"]
ignore = ["PLR0913", "PLR2004"]

[tool.mypy]
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unreachable = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
